### ISSUE TITLE
Opening lock does not work

### ISSUE THREAD

**Issue by manta42** [digaus/esphome-components-eqiva#10]
It doesn't work on the web, and when I implement it in esphome it remains the same,
ignores the opening...

![img 318](https://github.com/digaus/esphome-components-eqiva/assets/46687250/937124b2-0b41-4538-af63-ace094d7a42e)

When I close it it does so correctly.
![img 320](https://github.com/digaus/esphome-components-eqiva/assets/46687250/8359d28b-a9f9-4406-8a0e-ace2a049f39c)

In HA the button appears correctly - closed
![img 321](https://github.com/digaus/esphome-components-eqiva/assets/46687250/32ace5e2-fbb7-43b5-acad-b41d452fc25c)

If I manually press the lock to open, it opens the lock more turns than I have configured (2) and then ends up closing the lock. So it does appear closed on the HA button.
![img 322](https://github.com/digaus/esphome-components-eqiva/assets/46687250/1eb7bc5e-08ac-4e0a-8b83-294a1f7dbc27)

The lock control behavior is a bit strange,
It ignores the HA close button and if it opens, it does so with more turns than configured (2)
Do you know what could be happening? It is implemented in an esp wroom-32

Thank you,

**Comment by digaus** [comment]
Do you call open or unlock via HA? Open will turn until it cannot turn anymore to be able to open doors without a handle on the outside.

Unlock will turn as far as you configured. Are you sure that you have applied the settings? What is the behaviour with the original app?

**Comment by digaus** [comment]
Yes HA lock card uses open instead of unlock.

**Comment by manta42** [comment]
Sorry, now I have tried the original app and it works correctly... I have used esphome-components-eqiva again and it works correctly...
I don't know what I was doing wrong previously, but thanks for responding so quickly.

I already have the card integrated...it's fantastic.
![img 323](https://github.com/digaus/esphome-components-eqiva/assets/46687250/f7bbedbf-3e89-4231-88cf-913307be18df)


Thank you very much for your integration into HA...
