### ISSUE TITLE
Little bit more instructions would be good imho

### ISSUE THREAD

**Issue by KlausHans** [digaus/esphome-components-eqiva#14]
Hi, firstly, thank you very much for your work. It is the reason why i even ordered the lock.

As a newbie some more instructions would be helpful.
- is the app mandatory at any point?
- what are the requirements, what has to be already done with the lock (in regard of initial operation)?
- how can i use your css?
- the "First Pairing" section should be at the top, not at the bottom :)
- i recommend a hint to the example yaml. I first started to copy n paste the sections from the readme... 

-> I would wish for a more step by step instruction. That would be great. 

Thanks again.

**Comment by digaus** [comment]
1. No
2. Nothing
3. Need to check that. Currently I have them locally in HA and reference them in the Webserver part. 
4. For first pairing you need all other steps ;)
5. True will add a link in the readme

Someone posted a YouTube video a while back. But maybe I can make one too.

https://youtu.be/Ev7GehI4arM?si=q-5MG-ZeTJwoDtOR

**Comment by KlausHans** [comment]
Thanks for the clarification. A video (not in Spanish/Portuguese ;) ) would be great.

**Comment by digaus** [comment]
> Thanks for the clarification. A video (not in Spanish/Portuguese ;) ) would be great.

YouTube allows subtitles in your language but yeah a video would be nice.

I have a 2nd lock here which I need to integrate. Will do a video if I find the time

**Comment by KlausHans** [comment]
I've made it. Thank you again for this component, works very fine so far.
