### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by ldelvalleh** [digaus/esphome-components-eqiva#8]
Hello Digaus

Since there is no other way to contact you, I do it through an issue.

It was to thank you for this ESPHome component which I used to make this video https://youtu.be/Ev7GehI4arM?si=q-5MG-ZeTJwoDtOR

It is in Spanish but perhaps it will be useful to someone who is starting out.

That said, thank you very much for this development.

**Comment by digaus** [comment]
No Problem. I just did the port to esphome. Main work was done by others ^^


Btw I made custom js and CSS files for better UI.

Will post example.yaml soon :)


![IMG_4250](https://github.com/digaus/esphome-components-eqiva/assets/15358538/b1b71469-9ce4-4995-9748-9a7096ad0ee8)

![IMG_4251](https://github.com/digaus/esphome-components-eqiva/assets/15358538/9620ad24-e692-4e11-aed9-22b47fbf3870)


![IMG_4249](https://github.com/digaus/esphome-components-eqiva/assets/15358538/1ef37b6e-4b8a-4985-90cc-c109c62a16dd)

**Comment by digaus** [comment]
No Problem. I just did the port to esphome. Main work was done by others ^^


Btw I made custom js and CSS files for better UI.

Will post example.yaml soon :)


![IMG_4249](https://github.com/digaus/esphome-components-eqiva/assets/15358538/f1051f43-f706-4c59-8052-3107f4ac8fff)
![IMG_4250](https://github.com/digaus/esphome-components-eqiva/assets/15358538/2dd71d94-728e-44b3-8fb4-f0e9e66c9ce8)
![IMG_4251](https://github.com/digaus/esphome-components-eqiva/assets/15358538/31b964fd-b43b-44b4-9517-f884af06c136)

**Comment by digaus** [comment]
![IMG_3955](https://github.com/digaus/esphome-components-eqiva/assets/15358538/8241e9f0-2e38-4984-b09a-37a70f089c00)
![C7A295E8-D372-4431-99EB-27DA2031644E](https://github.com/digaus/esphome-components-eqiva/assets/15358538/80ef8046-74e8-4210-bbac-8b46123b5c80)
![IMG_3999](https://github.com/digaus/esphome-components-eqiva/assets/15358538/f83bf2e7-3add-44b8-b970-6d65bc171e6d)

![IMG_4183](https://github.com/digaus/esphome-components-eqiva/assets/15358538/af4072b2-4f5e-48b5-aeb9-c068dd38f765)
